# Generated by Django 5.2.8 on 2025-11-27 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tiene_aire', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('cantidad_personas', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('gerente', 'gerente'), ('recepcionista', 'recepcionista')], default='gerente', max_length=50),
        ),
        migrations.CreateModel(
            name='Orden_Lavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prendas', models.PositiveIntegerField()),
                ('valor_por_prenda', models.DecimalField(decimal_places=0, default=3000, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('lavado', 'Lavado')], default='en_espera', max_length=10)),
                ('huesped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.huesped')),
            ],
            options={
                'verbose_name': 'Orden Lavanderia',
                'verbose_name_plural': 'Ordenes Lavanderia',
            },
        ),
        migrations.CreateModel(
            name='Venta_Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('precio_pagado', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('transferencia', 'transferencia')], default='efectivo', max_length=20)),
                ('tipo_estadia', models.CharField(choices=[('dos_horas', 'Dos Horas'), ('estadia', 'Estadía')], default='estadia', max_length=20)),
                ('extras', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.habitacion')),
                ('huesped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.huesped')),
            ],
            options={
                'verbose_name': 'Venta Habitacion',
                'verbose_name_plural': 'Ventas Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Venta_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_pagado', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('transferencia', 'transferencia')], default='efectivo', max_length=20)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('huesped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.huesped')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
            ],
            options={
                'verbose_name': 'Venta Producto',
                'verbose_name_plural': 'Ventas Productos',
            },
        ),
    ]
