# Generated by Django 5.2.8 on 2025-11-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tiene_aire', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('cantidad_personas', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Venta_Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('precio_pagado', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('transferencia', 'transferencia')], default='efectivo', max_length=20)),
                ('tipo_estadia', models.CharField(choices=[('dos_horas', 'Dos Horas'), ('estadia', 'Estadía')], default='estadia', max_length=20)),
                ('extras', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitaciones.habitacion')),
                ('huesped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitaciones.huesped')),
            ],
            options={
                'verbose_name': 'Venta Habitacion',
                'verbose_name_plural': 'Ventas Habitaciones',
            },
        ),
    ]
