# Generated by Django 5.2.8 on 2025-12-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huesped',
            options={'verbose_name': 'Huesped', 'verbose_name_plural': 'Huespedes'},
        ),
        migrations.AlterField(
            model_name='huesped',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta_habitacion',
            name='extras',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta_habitacion',
            name='precio_pagado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
