# Generated by Django 5.2.8 on 2025-12-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
    ]
