# Generated by Django 5.2.8 on 2025-11-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_Lavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prendas', models.PositiveIntegerField()),
                ('valor_por_prenda', models.DecimalField(decimal_places=0, default=3000, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('lavado', 'Lavado')], default='en_espera', max_length=10)),
                ('huesped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitaciones.huesped')),
            ],
            options={
                'verbose_name': 'Orden Lavanderia',
                'verbose_name_plural': 'Ordenes Lavanderia',
            },
        ),
    ]
