# Generated by Django 5.2.8 on 2025-12-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_lavanderia',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
