# Generated by Django 5.2.8 on 2025-11-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Venta_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_pagado', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('transferencia', 'transferencia')], default='efectivo', max_length=20)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('huesped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habitaciones.huesped')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Venta Producto',
                'verbose_name_plural': 'Ventas Productos',
            },
        ),
    ]
